export type DriverStanding = {
    driver_id: string;
    driver_name: string;
    team_id: string | null;
    team_name: string;
    team_color: string;
    season_id: string;
    position: number;
    points: number;
    wins: number;
    podiums: number;
    starts: number;
    dnf_count: number;
    poles: number;
    diff_to_leader: number | null;
};
export type TeamStanding = {
    team_id: string;
    team_name: string;
    team_color: string;
    season_id: string;
    position: number;
    points: number;
    wins: number;
    podiums: number;
    starts: number;
    diff_to_leader: number | null;
};
export type RaceResult = {
    result_id: string;
    session_id: string;
    season_id: string;
    round_number: number;
    race_name: string;
    circuit_name: string | null;
    race_date: string | null;
    finish_position: number | null;
    position_display: string;
    driver_id: string;
    driver_name: string;
    car_number: number | null;
    team_id: string;
    team_name: string;
    team_color: string;
    grid_position: number | null;
    gap_to_leader: string | null;
    status: string | null;
    points_awarded: number;
    fastest_lap: boolean;
};
export declare const useDriverStandings: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<DriverStanding[], Error>;
export declare const useTeamStandings: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<TeamStanding[], Error>;
export declare const useRaceResults: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<RaceResult[], Error>;
