export type DriverStanding = {
    driver_id: string;
    driver_name: string;
    team_id: string | null;
    team_name: string;
    team_color: string;
    season_id: string;
    position: number;
    points: number;
    wins: number;
    podiums: number;
    starts: number;
    dnf_count: number;
    poles: number;
    diff_to_leader: number | null;
    is_manual_override: boolean;
    manual_points: number | null;
    manual_position: number | null;
    computed_points: number;
    computed_position: number;
};
export type TeamStanding = {
    team_id: string;
    team_name: string;
    team_color: string;
    season_id: string;
    position: number;
    points: number;
    wins: number;
    podiums: number;
    starts: number;
    diff_to_leader: number | null;
    is_manual_override: boolean;
    manual_points: number | null;
    manual_position: number | null;
    computed_points: number;
    computed_position: number;
};
export type RaceResult = {
    result_id: string;
    session_id: string;
    season_id: string;
    round_number: number;
    race_name: string;
    circuit_name: string | null;
    race_date: string | null;
    finish_position: number | null;
    position_display: string;
    driver_id: string;
    driver_name: string;
    car_number: number | null;
    team_id: string;
    team_name: string;
    team_color: string;
    grid_position: number | null;
    gap_to_leader: string | null;
    status: string | null;
    points_awarded: number;
    fastest_lap: boolean;
};
export declare const fetchDriverStandings: (seasonId: string) => Promise<DriverStanding[]>;
export declare const fetchTeamStandings: (seasonId: string) => Promise<TeamStanding[]>;
export declare const fetchRaceResults: (seasonId: string) => Promise<RaceResult[]>;
export declare const useDriverStandings: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<DriverStanding[], Error>;
export declare const useTeamStandings: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<TeamStanding[], Error>;
export declare const useRaceResults: (seasonId?: string) => import("@tanstack/react-query").UseQueryResult<RaceResult[], Error>;
