import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight, Wallet2 } from "lucide-react";
import { formatCurrency } from "../../features/markets/utils/format";
import { OutcomeTile } from "./OutcomeTile";
const statusClasses = {
    open: "bg-primary-container text-on-primary border-primary-container/50",
    closing_soon: "bg-surface-high text-primary-dim border-primary-dim/35",
    closed: "bg-surface-highest text-on-subtle border-white/10",
    settled: "bg-white/5 text-white border-white/10"
};
export function MarketCard({ id, name, closeTimeLabel, status, totalPool, commission, outcomes, selectedOutcomeId, onSelectOutcome, onViewDetails, actionLabel = "Inspect", subtitle }) {
    return (_jsx("article", { className: "prismatic-card p-5 lg:p-6", children: _jsxs("div", { className: "relative z-10 grid gap-6 xl:grid-cols-[minmax(17rem,21rem)_minmax(0,1fr)] xl:items-stretch", children: [_jsxs("div", { className: "flex h-full flex-col justify-between gap-6 border-b border-white/8 pb-6 xl:border-b-0 xl:border-r xl:pb-0 xl:pr-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex flex-wrap items-start justify-between gap-3", children: [_jsxs("div", { className: "min-w-0", children: [subtitle ? _jsx("p", { className: "prismatic-kicker text-primary-dim", children: subtitle }) : null, _jsx("h3", { className: "mt-3 line-clamp-3 font-headline text-[1.55rem] font-extrabold uppercase tracking-[0.04em] text-white sm:text-[1.7rem]", children: name }), closeTimeLabel ? (_jsx("p", { className: "mt-3 text-[0.72rem] uppercase tracking-[0.16em] text-on-subtle", children: closeTimeLabel })) : null] }), status ? (_jsx("span", { className: `inline-flex min-h-[2rem] items-center border px-3 text-[0.64rem] font-headline font-bold uppercase tracking-[0.16em] ${statusClasses[status]}`, children: status.replace("_", " ") })) : null] }), _jsxs("div", { className: "grid gap-3 sm:grid-cols-2", children: [_jsxs("div", { className: "flex items-center gap-3 border border-white/10 bg-surface px-4 py-3", children: [_jsx(Wallet2, { className: "h-4 w-4 text-primary-dim" }), _jsxs("div", { children: [_jsx("p", { className: "prismatic-kicker text-[0.56rem]", children: "Pool Liquidity" }), _jsx("p", { className: "mt-1 text-lg font-semibold text-white", children: formatCurrency(totalPool) })] })] }), _jsxs("div", { className: "border border-white/10 bg-surface px-4 py-3", children: [_jsx("p", { className: "prismatic-kicker text-[0.56rem]", children: "Commission" }), _jsxs("p", { className: "mt-1 text-lg font-semibold text-white", children: [commission.toFixed(1), "%"] })] })] })] }), onViewDetails ? (_jsxs("button", { type: "button", onClick: () => onViewDetails?.(id), className: "prismatic-button prismatic-button-secondary min-h-[2.9rem] w-full px-4 text-[0.62rem] sm:w-auto", children: [actionLabel, _jsx(ArrowRight, { className: "h-3.5 w-3.5" })] })) : null] }), _jsx("div", { className: "grid gap-3 sm:grid-cols-2 2xl:grid-cols-4", children: outcomes.map((outcome) => (_jsx(OutcomeTile, { ...outcome, isSelected: selectedOutcomeId === outcome.outcomeId, onSelect: outcome.onSelect ?? (() => onSelectOutcome?.(outcome.outcomeId)) }, outcome.id))) })] }) }));
}
