import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight, Wallet2 } from "lucide-react";
import { formatCurrency } from "../../features/markets/utils/format";
import { OutcomeTile } from "./OutcomeTile";
const statusClasses = {
    open: "bg-primary-container text-on-primary border-primary-container/50",
    closing_soon: "bg-surface-high text-primary-dim border-primary-dim/35",
    closed: "bg-surface-highest text-on-subtle border-white/10",
    settled: "bg-white/5 text-white border-white/10"
};
export function MarketCard({ id, name, closeTimeLabel, status, totalPool, commission, outcomes, selectedOutcomeId, onSelectOutcome, onViewDetails, actionLabel = "Inspect", subtitle }) {
    return (_jsx("article", { className: "prismatic-card flex h-full flex-col p-5", children: _jsxs("div", { className: "relative z-10 flex h-full flex-col", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "min-w-0", children: [subtitle ? _jsx("p", { className: "prismatic-kicker text-primary-dim", children: subtitle }) : null, _jsx("h3", { className: "mt-3 line-clamp-2 font-headline text-[1.65rem] font-extrabold uppercase tracking-[0.04em] text-white", children: name }), closeTimeLabel ? (_jsx("p", { className: "mt-2 text-[0.72rem] uppercase tracking-[0.16em] text-on-subtle", children: closeTimeLabel })) : null] }), _jsxs("div", { className: "flex flex-col items-end gap-3", children: [status ? (_jsx("span", { className: `inline-flex min-h-[2rem] items-center border px-3 text-[0.64rem] font-headline font-bold uppercase tracking-[0.16em] ${statusClasses[status]}`, children: status.replace("_", " ") })) : null, _jsxs("div", { className: "flex items-center gap-2 border border-white/10 bg-surface px-3 py-2 text-right", children: [_jsx(Wallet2, { className: "h-4 w-4 text-primary-dim" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-white", children: formatCurrency(totalPool) }), _jsx("p", { className: "text-[0.6rem] uppercase tracking-[0.16em] text-on-subtle", children: "Pool" })] })] })] })] }), _jsx("div", { className: "mt-6 grid gap-3", children: outcomes.map((outcome) => (_jsx(OutcomeTile, { ...outcome, isSelected: selectedOutcomeId === outcome.outcomeId, onSelect: outcome.onSelect ?? (() => onSelectOutcome?.(outcome.outcomeId)) }, outcome.id))) }), _jsxs("div", { className: "mt-6 flex items-center justify-between border-t border-white/5 pt-4", children: [_jsxs("div", { children: [_jsx("p", { className: "prismatic-kicker text-[0.58rem]", children: "Commission" }), _jsxs("p", { className: "mt-1 text-lg font-semibold text-white", children: [commission.toFixed(1), "%"] })] }), onViewDetails ? (_jsxs("button", { type: "button", onClick: () => onViewDetails?.(id), className: "prismatic-button prismatic-button-secondary min-h-[2.6rem] px-4 text-[0.62rem]", children: [actionLabel, _jsx(ArrowRight, { className: "h-3.5 w-3.5" })] })) : null] })] }) }));
}
