import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowUpRight, Gem } from "lucide-react";
export function OutcomeTile({ teamCode, teamName, teamColor, driverName, oddsLabel, poolShareLabel, poolSharePercent, isFavourite, isBestPayout, isSelected, onSelect }) {
    const teamLine = `${teamCode.toUpperCase()} • ${teamName}`;
    return (_jsxs("button", { type: "button", onClick: () => onSelect?.(), style: { "--team-color": teamColor ?? "#94a3b8" }, className: `outcome-tile group flex min-h-[7.1rem] cursor-pointer flex-col justify-between border p-4 text-left transition ${isSelected
            ? "border-primary-container/50 bg-surface-high text-white"
            : "border-white/10 bg-surface-low/70 text-white hover:bg-surface"}`, children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { "aria-hidden": true, className: "inline-flex h-2 w-2 shrink-0", style: { backgroundColor: teamColor ?? "#94a3b8" } }), _jsx("span", { className: "truncate font-headline text-[0.74rem] font-bold uppercase tracking-[0.16em] text-on-subtle", title: teamLine, children: teamCode })] }), _jsx("p", { className: "mt-3 line-clamp-2 min-h-[3.2rem] font-headline text-base font-extrabold uppercase tracking-[0.05em] text-white sm:text-lg", children: driverName }), _jsx("p", { className: "mt-1 line-clamp-2 min-h-[2rem] text-[0.68rem] uppercase tracking-[0.14em] text-on-subtle", children: teamName })] }), _jsxs("div", { className: "flex flex-col items-end gap-1 text-primary-dim", children: [isFavourite ? _jsx(Gem, { className: "h-3.5 w-3.5" }) : null, isBestPayout ? _jsx(ArrowUpRight, { className: "h-3.5 w-3.5" }) : null] })] }), _jsxs("div", { className: "mt-4", children: [_jsxs("div", { className: "flex items-end justify-between gap-3", children: [_jsx("span", { className: "font-headline text-[1.75rem] font-extrabold text-white", children: oddsLabel }), _jsx("span", { className: "text-right text-[0.66rem] uppercase tracking-[0.14em] text-on-subtle", children: poolShareLabel })] }), _jsx("div", { className: "mt-3 h-1 bg-white/10", children: _jsx("div", { className: "h-full", style: {
                                width: `${Math.max(0, Math.min(poolSharePercent, 100))}%`,
                                backgroundColor: teamColor ?? "#00f2ff"
                            } }) })] })] }));
}
