import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams } from "react-router-dom";
import { useBettingRealtime } from "@domains/betting/hooks/useBettingRealtime";
import { useBettingStore } from "@domains/betting/store/bettingStore";
const MarketDetailPage = () => {
    const { marketId } = useParams();
    useBettingRealtime(marketId);
    const market = useBettingStore((state) => state.markets.find((m) => m.id === marketId));
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("header", { className: "flex flex-wrap items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-widest text-white/60", children: "Market" }), _jsx("h1", { className: "text-3xl font-semibold", children: market?.name ?? "Loading" }), _jsx("p", { className: "text-white/60", children: market?.eventId })] }), _jsxs("div", { className: "rounded-3xl border border-white/10 bg-black/30 px-6 py-4 text-right", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-white/60", children: "Total Pool" }), _jsxs("p", { className: "text-2xl font-semibold", children: ["\u0189", market?.totalPool.toLocaleString() ?? "—"] })] })] }), _jsxs("section", { className: "grid gap-8 lg:grid-cols-[2fr,1fr]", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-sm text-white/60", children: "Outcome cards & tote analytics will stream in via realtime feeds." }), _jsx("div", { className: "rounded-3xl border border-dashed border-white/20 p-10 text-center text-white/50", children: "Outcome grid placeholder" })] }), _jsxs("aside", { className: "rounded-3xl border border-white/10 bg-black/40 p-6 shadow-2xl shadow-black/30", children: [_jsx("h2", { className: "text-xl font-semibold", children: "Bet Slip" }), _jsx("p", { className: "mt-2 text-sm text-white/60", children: "Select an outcome to preview odds & estimated payout." }), _jsxs("form", { className: "mt-6 space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "text-xs uppercase tracking-[0.3em] text-white/50", children: "Stake" }), _jsx("input", { type: "number", placeholder: "100", className: "mt-2 w-full rounded-2xl border border-white/10 bg-black/60 px-4 py-3 text-white focus:border-brand focus:outline-none" })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3 text-sm", children: [_jsx(Stat, { label: "Baseline", value: "\u2014" }), _jsx(Stat, { label: "Effective", value: "\u2014" }), _jsx(Stat, { label: "Price Impact", value: "\u2014" }), _jsx(Stat, { label: "Payout", value: "\u2014" })] }), _jsx("button", { type: "button", className: "w-full rounded-2xl bg-brand py-3 text-center text-base font-semibold uppercase tracking-widest text-black disabled:opacity-40", disabled: true, children: "Place Wager" })] })] })] })] }));
};
const Stat = ({ label, value }) => (_jsxs("div", { className: "rounded-2xl border border-white/10 bg-white/5 p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-white/60", children: label }), _jsx("p", { className: "mt-1 text-lg font-semibold", children: value })] }));
export default MarketDetailPage;
